### ISSUE TITLE
Dataset Details

### ISSUE THREAD

**Issue by gmihaila** [gmihaila/stock_risk_prediction#1]
Possible data source:
10-K parse files at https://sraf.nd.edu/data/  (#2 in the link)

* It has elaborate description about how he cleaned the file. 
* Our sample will be all firms from 2005 -2018 that have filed their 10-K reports only.  
* Section 1A (risk section) of 10K is what we are interested in. * Section 1A  reporting became mandatory from 2005. 
* Some of the firms in 2005 may not have section 1A in their 10K reports. You can skip those as well for now. 
* The firms  have voluntarily disclosed  the risk info before 2005  in Item 1: Business section but it is not that structured.

**Comment by gmihaila** [comment]
@Jagdish05 Dr. Albert suggested we could use the data from [stock2vec](https://towardsdatascience.com/stock2vec-from-ml-to-p-e-2e6ba407c24), but unfortunately the link is not available anymore.

I looked at [Quandl](https://www.quandl.com/product/WIKIP/WIKI/PRICES) and found a way to download some csv's: https://blog.quandl.com/getting-started-with-the-quandl-api

I will do a little more research to figure out what would be the input - output of the model, where would we get the risk from.

**Comment by Jagdish05** [comment]
sure I also try to find other dataset

**Comment by gmihaila** [comment]
@Jagdish05 Did you find any datasets? You said you will try to find other datasets. How did that work? Can you please share some findings with me? Maybe they are better.

**Comment by gmihaila** [comment]
My findings:

* Main Dataset: [S&P 500 stock data](https://www.kaggle.com/camnugent/sandp500)

* Download detailes for each company: [S&P 500 Companies with Financial Information](https://datahub.io/core/s-and-p-500-companies-financials#resource-s-and-p-500-companies-financials_zip)

**Comment by Jagdish05** [comment]
I tried to find dataset but i didn’t make out
